function [ binaryVector ] = huffmanEncoder( imgBW, codeBook )
%%
%This function encodes a black n white image into a single binary vector
% Input: 'bwImg' is black image, e.g. a Y frame of a YUV image
%        'CodeBook', is the codebook/dictionary generated by huffmanCodebook

% Output: encoded bwImg, a binary vector formed by concatenated huffman codewords 

[height, width] = size(imgBW);

placeholder = cell(height, width);

for i = 1: length(codeBook)
    codeWord = codeBook(i, 2);
    logical = imgBW == codeBook{i,1};
    placeholder(logical) = codeWord;
end

binaryVector = reshape(placeholder, 1, []);
binaryVector = cell2mat(binaryVector);



